services:
 
  search-google:
    build: ./search-google
    container_name: search-google
    ports:
      - "8082:8082"
    networks:
      - leads-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}"
        labels: "service={{.Name}}"

networks:
  leads-network:
    driver: bridge

